package utn.sau.hp.com.modelo;
// Generated 04/12/2014 23:31:51 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Actividades generated by hbm2java
 */
public class Actividades  implements java.io.Serializable {


     private Integer id;
     private Areas areas;
     private String actividadDescripcion;
     private Set tareases = new HashSet(0);

    public Actividades() {
    }

	
    public Actividades(Areas areas, String actividadDescripcion) {
        this.areas = areas;
        this.actividadDescripcion = actividadDescripcion;
    }
    public Actividades(Areas areas, String actividadDescripcion, Set tareases) {
       this.areas = areas;
       this.actividadDescripcion = actividadDescripcion;
       this.tareases = tareases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Areas getAreas() {
        return this.areas;
    }
    
    public void setAreas(Areas areas) {
        this.areas = areas;
    }
    public String getActividadDescripcion() {
        return this.actividadDescripcion;
    }
    
    public void setActividadDescripcion(String actividadDescripcion) {
        this.actividadDescripcion = actividadDescripcion;
    }
    public Set getTareases() {
        return this.tareases;
    }
    
    public void setTareases(Set tareases) {
        this.tareases = tareases;
    }




}


