package utn.sau.hp.com.modelo;
// Generated 04/12/2014 23:31:51 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {


     private Integer id;
     private Localidades localidades;
     private int carreraId;
     private int nroLegajo;
     private String apellido;
     private String nombre;
     private Date fechaNacimiento;
     private int dni;
     private String direccion;
     private String correoElectronico;
     private String telefono;
     private Byte suscripcion;
     private byte[] alumnoCv;
     private String password;
     private Long cuil;
     private Set conveniosparticulareses = new HashSet(0);
     private Set postulacioneses = new HashSet(0);
     private Set alumnosmateriases = new HashSet(0);

    public Alumnos() {
    }

	
    public Alumnos(int carreraId, int nroLegajo, String apellido, String nombre, Date fechaNacimiento, int dni, String password) {
        this.carreraId = carreraId;
        this.nroLegajo = nroLegajo;
        this.apellido = apellido;
        this.nombre = nombre;
        this.fechaNacimiento = fechaNacimiento;
        this.dni = dni;
        this.password = password;
    }
    public Alumnos(Localidades localidades, int carreraId, int nroLegajo, String apellido, String nombre, Date fechaNacimiento, int dni, String direccion, String correoElectronico, String telefono, Byte suscripcion, byte[] alumnoCv, String password, Long cuil, Set conveniosparticulareses, Set postulacioneses, Set alumnosmateriases) {
       this.localidades = localidades;
       this.carreraId = carreraId;
       this.nroLegajo = nroLegajo;
       this.apellido = apellido;
       this.nombre = nombre;
       this.fechaNacimiento = fechaNacimiento;
       this.dni = dni;
       this.direccion = direccion;
       this.correoElectronico = correoElectronico;
       this.telefono = telefono;
       this.suscripcion = suscripcion;
       this.alumnoCv = alumnoCv;
       this.password = password;
       this.cuil = cuil;
       this.conveniosparticulareses = conveniosparticulareses;
       this.postulacioneses = postulacioneses;
       this.alumnosmateriases = alumnosmateriases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Localidades getLocalidades() {
        return this.localidades;
    }
    
    public void setLocalidades(Localidades localidades) {
        this.localidades = localidades;
    }
    public int getCarreraId() {
        return this.carreraId;
    }
    
    public void setCarreraId(int carreraId) {
        this.carreraId = carreraId;
    }
    public int getNroLegajo() {
        return this.nroLegajo;
    }
    
    public void setNroLegajo(int nroLegajo) {
        this.nroLegajo = nroLegajo;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Byte getSuscripcion() {
        return this.suscripcion;
    }
    
    public void setSuscripcion(Byte suscripcion) {
        this.suscripcion = suscripcion;
    }
    public byte[] getAlumnoCv() {
        return this.alumnoCv;
    }
    
    public void setAlumnoCv(byte[] alumnoCv) {
        this.alumnoCv = alumnoCv;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Long getCuil() {
        return this.cuil;
    }
    
    public void setCuil(Long cuil) {
        this.cuil = cuil;
    }
    public Set getConveniosparticulareses() {
        return this.conveniosparticulareses;
    }
    
    public void setConveniosparticulareses(Set conveniosparticulareses) {
        this.conveniosparticulareses = conveniosparticulareses;
    }
    public Set getPostulacioneses() {
        return this.postulacioneses;
    }
    
    public void setPostulacioneses(Set postulacioneses) {
        this.postulacioneses = postulacioneses;
    }
    public Set getAlumnosmateriases() {
        return this.alumnosmateriases;
    }
    
    public void setAlumnosmateriases(Set alumnosmateriases) {
        this.alumnosmateriases = alumnosmateriases;
    }




}


