package utn.sau.hp.com.modelo;
// Generated 04/12/2014 23:31:51 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Alumnosmaterias generated by hbm2java
 */
public class Alumnosmaterias  implements java.io.Serializable {


     private Integer id;
     private Alumnos alumnos;
     private Materias materias;
     private String estadoMateria;
     private Date fechaRegularizacion;
     private Date fechaAprobacion;

    public Alumnosmaterias() {
    }

    public Alumnosmaterias(Alumnos alumnos, Materias materias, String estadoMateria, Date fechaRegularizacion, Date fechaAprobacion) {
       this.alumnos = alumnos;
       this.materias = materias;
       this.estadoMateria = estadoMateria;
       this.fechaRegularizacion = fechaRegularizacion;
       this.fechaAprobacion = fechaAprobacion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
    public Materias getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(Materias materias) {
        this.materias = materias;
    }
    public String getEstadoMateria() {
        return this.estadoMateria;
    }
    
    public void setEstadoMateria(String estadoMateria) {
        this.estadoMateria = estadoMateria;
    }
    public Date getFechaRegularizacion() {
        return this.fechaRegularizacion;
    }
    
    public void setFechaRegularizacion(Date fechaRegularizacion) {
        this.fechaRegularizacion = fechaRegularizacion;
    }
    public Date getFechaAprobacion() {
        return this.fechaAprobacion;
    }
    
    public void setFechaAprobacion(Date fechaAprobacion) {
        this.fechaAprobacion = fechaAprobacion;
    }




}


