package utn.sau.hp.com.modelo;
// Generated 04/12/2014 23:31:51 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Anexos generated by hbm2java
 */
public class Anexos  implements java.io.Serializable {


     private Integer id;
     private Empresas empresas;
     private byte pagaSeguroTrabajoAnterior;
     private Byte pagaObraSocialAnterior;
     private Integer porcentajeGastoAnterior;
     private String anexoConvenioMarco;
     private Date convenioFechaAnterior;
     private Integer empresaCuit;

    public Anexos() {
    }

	
    public Anexos(Empresas empresas, byte pagaSeguroTrabajoAnterior) {
        this.empresas = empresas;
        this.pagaSeguroTrabajoAnterior = pagaSeguroTrabajoAnterior;
    }
    public Anexos(Empresas empresas, byte pagaSeguroTrabajoAnterior, Byte pagaObraSocialAnterior, Integer porcentajeGastoAnterior, String anexoConvenioMarco, Date convenioFechaAnterior, Integer empresaCuit) {
       this.empresas = empresas;
       this.pagaSeguroTrabajoAnterior = pagaSeguroTrabajoAnterior;
       this.pagaObraSocialAnterior = pagaObraSocialAnterior;
       this.porcentajeGastoAnterior = porcentajeGastoAnterior;
       this.anexoConvenioMarco = anexoConvenioMarco;
       this.convenioFechaAnterior = convenioFechaAnterior;
       this.empresaCuit = empresaCuit;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public byte getPagaSeguroTrabajoAnterior() {
        return this.pagaSeguroTrabajoAnterior;
    }
    
    public void setPagaSeguroTrabajoAnterior(byte pagaSeguroTrabajoAnterior) {
        this.pagaSeguroTrabajoAnterior = pagaSeguroTrabajoAnterior;
    }
    public Byte getPagaObraSocialAnterior() {
        return this.pagaObraSocialAnterior;
    }
    
    public void setPagaObraSocialAnterior(Byte pagaObraSocialAnterior) {
        this.pagaObraSocialAnterior = pagaObraSocialAnterior;
    }
    public Integer getPorcentajeGastoAnterior() {
        return this.porcentajeGastoAnterior;
    }
    
    public void setPorcentajeGastoAnterior(Integer porcentajeGastoAnterior) {
        this.porcentajeGastoAnterior = porcentajeGastoAnterior;
    }
    public String getAnexoConvenioMarco() {
        return this.anexoConvenioMarco;
    }
    
    public void setAnexoConvenioMarco(String anexoConvenioMarco) {
        this.anexoConvenioMarco = anexoConvenioMarco;
    }
    public Date getConvenioFechaAnterior() {
        return this.convenioFechaAnterior;
    }
    
    public void setConvenioFechaAnterior(Date convenioFechaAnterior) {
        this.convenioFechaAnterior = convenioFechaAnterior;
    }
    public Integer getEmpresaCuit() {
        return this.empresaCuit;
    }
    
    public void setEmpresaCuit(Integer empresaCuit) {
        this.empresaCuit = empresaCuit;
    }




}


