package utn.sau.hp.com.modelo;
// Generated 13/11/2014 15:37:16 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Anexos generated by hbm2java
 */
public class Anexos  implements java.io.Serializable {


     private Integer id;
     private Empresas empresas;
     private String anexoConvenioMarco;
     private Integer empresaCuit;
     private Byte convenioFechaAnterior;
     private Integer porcentajeGastoAnterior;
     private Byte pagaObraSocialAnterior;
     private byte pagaSeguroTrabajoAnterior;
     private boolean pagaAsignacionEstimuloAnterior;
     private Set firmanteses = new HashSet(0);

    public Anexos() {
    }

	
    public Anexos(Empresas empresas, byte pagaSeguroTrabajoAnterior, boolean pagaAsignacionEstimuloAnterior) {
        this.empresas = empresas;
        this.pagaSeguroTrabajoAnterior = pagaSeguroTrabajoAnterior;
        this.pagaAsignacionEstimuloAnterior = pagaAsignacionEstimuloAnterior;
    }
    public Anexos(Empresas empresas, String anexoConvenioMarco, Integer empresaCuit, Byte convenioFechaAnterior, Integer porcentajeGastoAnterior, Byte pagaObraSocialAnterior, byte pagaSeguroTrabajoAnterior, boolean pagaAsignacionEstimuloAnterior, Set firmanteses) {
       this.empresas = empresas;
       this.anexoConvenioMarco = anexoConvenioMarco;
       this.empresaCuit = empresaCuit;
       this.convenioFechaAnterior = convenioFechaAnterior;
       this.porcentajeGastoAnterior = porcentajeGastoAnterior;
       this.pagaObraSocialAnterior = pagaObraSocialAnterior;
       this.pagaSeguroTrabajoAnterior = pagaSeguroTrabajoAnterior;
       this.pagaAsignacionEstimuloAnterior = pagaAsignacionEstimuloAnterior;
       this.firmanteses = firmanteses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public String getAnexoConvenioMarco() {
        return this.anexoConvenioMarco;
    }
    
    public void setAnexoConvenioMarco(String anexoConvenioMarco) {
        this.anexoConvenioMarco = anexoConvenioMarco;
    }
    public Integer getEmpresaCuit() {
        return this.empresaCuit;
    }
    
    public void setEmpresaCuit(Integer empresaCuit) {
        this.empresaCuit = empresaCuit;
    }
    public Byte getConvenioFechaAnterior() {
        return this.convenioFechaAnterior;
    }
    
    public void setConvenioFechaAnterior(Byte convenioFechaAnterior) {
        this.convenioFechaAnterior = convenioFechaAnterior;
    }
    public Integer getPorcentajeGastoAnterior() {
        return this.porcentajeGastoAnterior;
    }
    
    public void setPorcentajeGastoAnterior(Integer porcentajeGastoAnterior) {
        this.porcentajeGastoAnterior = porcentajeGastoAnterior;
    }
    public Byte getPagaObraSocialAnterior() {
        return this.pagaObraSocialAnterior;
    }
    
    public void setPagaObraSocialAnterior(Byte pagaObraSocialAnterior) {
        this.pagaObraSocialAnterior = pagaObraSocialAnterior;
    }
    public byte getPagaSeguroTrabajoAnterior() {
        return this.pagaSeguroTrabajoAnterior;
    }
    
    public void setPagaSeguroTrabajoAnterior(byte pagaSeguroTrabajoAnterior) {
        this.pagaSeguroTrabajoAnterior = pagaSeguroTrabajoAnterior;
    }
    public boolean isPagaAsignacionEstimuloAnterior() {
        return this.pagaAsignacionEstimuloAnterior;
    }
    
    public void setPagaAsignacionEstimuloAnterior(boolean pagaAsignacionEstimuloAnterior) {
        this.pagaAsignacionEstimuloAnterior = pagaAsignacionEstimuloAnterior;
    }
    public Set getFirmanteses() {
        return this.firmanteses;
    }
    
    public void setFirmanteses(Set firmanteses) {
        this.firmanteses = firmanteses;
    }




}


