package utn.sau.hp.com.modelo;
// Generated 04/12/2014 23:31:51 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Areas generated by hbm2java
 */
public class Areas  implements java.io.Serializable {


     private Integer id;
     private Carreras carreras;
     private String areaDescripcion;
     private Set actividadeses = new HashSet(0);
     private Set competenciases = new HashSet(0);

    public Areas() {
    }

	
    public Areas(String areaDescripcion) {
        this.areaDescripcion = areaDescripcion;
    }
    public Areas(Carreras carreras, String areaDescripcion, Set actividadeses, Set competenciases) {
       this.carreras = carreras;
       this.areaDescripcion = areaDescripcion;
       this.actividadeses = actividadeses;
       this.competenciases = competenciases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Carreras getCarreras() {
        return this.carreras;
    }
    
    public void setCarreras(Carreras carreras) {
        this.carreras = carreras;
    }
    public String getAreaDescripcion() {
        return this.areaDescripcion;
    }
    
    public void setAreaDescripcion(String areaDescripcion) {
        this.areaDescripcion = areaDescripcion;
    }
    public Set getActividadeses() {
        return this.actividadeses;
    }
    
    public void setActividadeses(Set actividadeses) {
        this.actividadeses = actividadeses;
    }
    public Set getCompetenciases() {
        return this.competenciases;
    }
    
    public void setCompetenciases(Set competenciases) {
        this.competenciases = competenciases;
    }




}


