package utn.sau.hp.com.modelo;
// Generated 13/11/2014 15:37:16 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Carreras generated by hbm2java
 */
public class Carreras  implements java.io.Serializable {


     private int id;
     private String carrera;
     private Set alumnoses = new HashSet(0);
     private Set conveniosparticulareses = new HashSet(0);
     private Set ofertascarrerases = new HashSet(0);

    public Carreras() {
    }

	
    public Carreras(int id, String carrera) {
        this.id = id;
        this.carrera = carrera;
    }
    public Carreras(int id, String carrera, Set alumnoses, Set conveniosparticulareses, Set ofertascarrerases) {
       this.id = id;
       this.carrera = carrera;
       this.alumnoses = alumnoses;
       this.conveniosparticulareses = conveniosparticulareses;
       this.ofertascarrerases = ofertascarrerases;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }
    public Set getAlumnoses() {
        return this.alumnoses;
    }
    
    public void setAlumnoses(Set alumnoses) {
        this.alumnoses = alumnoses;
    }
    public Set getConveniosparticulareses() {
        return this.conveniosparticulareses;
    }
    
    public void setConveniosparticulareses(Set conveniosparticulareses) {
        this.conveniosparticulareses = conveniosparticulareses;
    }
    public Set getOfertascarrerases() {
        return this.ofertascarrerases;
    }
    
    public void setOfertascarrerases(Set ofertascarrerases) {
        this.ofertascarrerases = ofertascarrerases;
    }




}


