package utn.sau.hp.com.modelo;
// Generated 13/11/2014 15:37:16 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Conveniosparticulares generated by hbm2java
 */
public class Conveniosparticulares  implements java.io.Serializable {


     private Integer id;
     private Tutores tutores;
     private Empresas empresas;
     private Alumnos alumnos;
     private Carreras carreras;
     private Ofertas ofertas;
     private Date fechaInicio;
     private Date fechaFin;
     private Integer importeAsignacionEstimulo;
     private String nombreArt;
     private int importeArt;
     private String nombreObraSocial;
     private int importeObraSocial;
     private Date fechaCancelacion;
     private String motivoCancelacion;
     private String evaluacionAlumno;
     private Date fechaFirmaConvenio;
     private byte[] archivoCp;
     private Date fechaAltaObraSocial;
     private Boolean pagaAsignacionEstumulo;
     private Set adendases = new HashSet(0);
     private Set pagosArtses = new HashSet(0);
     private Set tareases = new HashSet(0);

    public Conveniosparticulares() {
    }

	
    public Conveniosparticulares(Tutores tutores, Empresas empresas, Alumnos alumnos, Carreras carreras, int importeArt, int importeObraSocial, String evaluacionAlumno) {
        this.tutores = tutores;
        this.empresas = empresas;
        this.alumnos = alumnos;
        this.carreras = carreras;
        this.importeArt = importeArt;
        this.importeObraSocial = importeObraSocial;
        this.evaluacionAlumno = evaluacionAlumno;
    }
    public Conveniosparticulares(Tutores tutores, Empresas empresas, Alumnos alumnos, Carreras carreras, Ofertas ofertas, Date fechaInicio, Date fechaFin, Integer importeAsignacionEstimulo, String nombreArt, int importeArt, String nombreObraSocial, int importeObraSocial, Date fechaCancelacion, String motivoCancelacion, String evaluacionAlumno, Date fechaFirmaConvenio, byte[] archivoCp, Date fechaAltaObraSocial, Boolean pagaAsignacionEstumulo, Set adendases, Set pagosArtses, Set tareases) {
       this.tutores = tutores;
       this.empresas = empresas;
       this.alumnos = alumnos;
       this.carreras = carreras;
       this.ofertas = ofertas;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.importeAsignacionEstimulo = importeAsignacionEstimulo;
       this.nombreArt = nombreArt;
       this.importeArt = importeArt;
       this.nombreObraSocial = nombreObraSocial;
       this.importeObraSocial = importeObraSocial;
       this.fechaCancelacion = fechaCancelacion;
       this.motivoCancelacion = motivoCancelacion;
       this.evaluacionAlumno = evaluacionAlumno;
       this.fechaFirmaConvenio = fechaFirmaConvenio;
       this.archivoCp = archivoCp;
       this.fechaAltaObraSocial = fechaAltaObraSocial;
       this.pagaAsignacionEstumulo = pagaAsignacionEstumulo;
       this.adendases = adendases;
       this.pagosArtses = pagosArtses;
       this.tareases = tareases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tutores getTutores() {
        return this.tutores;
    }
    
    public void setTutores(Tutores tutores) {
        this.tutores = tutores;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
    public Carreras getCarreras() {
        return this.carreras;
    }
    
    public void setCarreras(Carreras carreras) {
        this.carreras = carreras;
    }
    public Ofertas getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Ofertas ofertas) {
        this.ofertas = ofertas;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Integer getImporteAsignacionEstimulo() {
        return this.importeAsignacionEstimulo;
    }
    
    public void setImporteAsignacionEstimulo(Integer importeAsignacionEstimulo) {
        this.importeAsignacionEstimulo = importeAsignacionEstimulo;
    }
    public String getNombreArt() {
        return this.nombreArt;
    }
    
    public void setNombreArt(String nombreArt) {
        this.nombreArt = nombreArt;
    }
    public int getImporteArt() {
        return this.importeArt;
    }
    
    public void setImporteArt(int importeArt) {
        this.importeArt = importeArt;
    }
    public String getNombreObraSocial() {
        return this.nombreObraSocial;
    }
    
    public void setNombreObraSocial(String nombreObraSocial) {
        this.nombreObraSocial = nombreObraSocial;
    }
    public int getImporteObraSocial() {
        return this.importeObraSocial;
    }
    
    public void setImporteObraSocial(int importeObraSocial) {
        this.importeObraSocial = importeObraSocial;
    }
    public Date getFechaCancelacion() {
        return this.fechaCancelacion;
    }
    
    public void setFechaCancelacion(Date fechaCancelacion) {
        this.fechaCancelacion = fechaCancelacion;
    }
    public String getMotivoCancelacion() {
        return this.motivoCancelacion;
    }
    
    public void setMotivoCancelacion(String motivoCancelacion) {
        this.motivoCancelacion = motivoCancelacion;
    }
    public String getEvaluacionAlumno() {
        return this.evaluacionAlumno;
    }
    
    public void setEvaluacionAlumno(String evaluacionAlumno) {
        this.evaluacionAlumno = evaluacionAlumno;
    }
    public Date getFechaFirmaConvenio() {
        return this.fechaFirmaConvenio;
    }
    
    public void setFechaFirmaConvenio(Date fechaFirmaConvenio) {
        this.fechaFirmaConvenio = fechaFirmaConvenio;
    }
    public byte[] getArchivoCp() {
        return this.archivoCp;
    }
    
    public void setArchivoCp(byte[] archivoCp) {
        this.archivoCp = archivoCp;
    }
    public Date getFechaAltaObraSocial() {
        return this.fechaAltaObraSocial;
    }
    
    public void setFechaAltaObraSocial(Date fechaAltaObraSocial) {
        this.fechaAltaObraSocial = fechaAltaObraSocial;
    }
    public Boolean getPagaAsignacionEstumulo() {
        return this.pagaAsignacionEstumulo;
    }
    
    public void setPagaAsignacionEstumulo(Boolean pagaAsignacionEstumulo) {
        this.pagaAsignacionEstumulo = pagaAsignacionEstumulo;
    }
    public Set getAdendases() {
        return this.adendases;
    }
    
    public void setAdendases(Set adendases) {
        this.adendases = adendases;
    }
    public Set getPagosArtses() {
        return this.pagosArtses;
    }
    
    public void setPagosArtses(Set pagosArtses) {
        this.pagosArtses = pagosArtses;
    }
    public Set getTareases() {
        return this.tareases;
    }
    
    public void setTareases(Set tareases) {
        this.tareases = tareases;
    }




}


