package utn.sau.hp.com.modelo;
// Generated 13/11/2014 15:37:16 by Hibernate Tools 3.6.0



/**
 * Departamentos generated by hbm2java
 */
public class Departamentos  implements java.io.Serializable {


     private int id;
     private int provinciaId;
     private String nombre;

    public Departamentos() {
    }

    public Departamentos(int id, int provinciaId, String nombre) {
       this.id = id;
       this.provinciaId = provinciaId;
       this.nombre = nombre;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getProvinciaId() {
        return this.provinciaId;
    }
    
    public void setProvinciaId(int provinciaId) {
        this.provinciaId = provinciaId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


