package utn.sau.hp.com.modelo;
// Generated 04/12/2014 23:31:51 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos  implements java.io.Serializable {


     private Integer id;
     private Provincias provincias;
     private String nombre;
     private Set localidadeses = new HashSet(0);

    public Departamentos() {
    }

	
    public Departamentos(Provincias provincias) {
        this.provincias = provincias;
    }
    public Departamentos(Provincias provincias, String nombre, Set localidadeses) {
       this.provincias = provincias;
       this.nombre = nombre;
       this.localidadeses = localidadeses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Provincias getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Provincias provincias) {
        this.provincias = provincias;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getLocalidadeses() {
        return this.localidadeses;
    }
    
    public void setLocalidadeses(Set localidadeses) {
        this.localidadeses = localidadeses;
    }




}


