package utn.sau.hp.com.modelo;
// Generated 04/12/2014 23:31:51 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresas generated by hbm2java
 */
public class Empresas  implements java.io.Serializable {


     private Integer id;
     private Localidades localidades;
     private long empresaCuit;
     private Date convenioFecha;
     private Integer porcentajeGasto;
     private String empresaRazonSocial;
     private String empresaActividad;
     private String empresaDireccion;
     private String empresaCorreo;
     private String empresaTelefono;
     private String representanteNombre;
     private Integer representanteDni;
     private byte pagaObraSocial;
     private byte pagaSeguroTrabajo;
     private byte pagaAsignacionEstimulo;
     private Date convenioFechaBaja;
     private String motivoBaja;
     private String password;
     private byte[] archivoCm;
     private String contactoNombre;
     private String contactoCorreo;
     private String contactoTelefono;
     private Set ofertases = new HashSet(0);
     private Set anexoses = new HashSet(0);
     private Set estadocuentases = new HashSet(0);
     private Set firmanteses = new HashSet(0);
     private Set conveniosparticulareses = new HashSet(0);

    public Empresas() {
    }

	
    public Empresas(Localidades localidades, long empresaCuit, String empresaRazonSocial, byte pagaObraSocial, byte pagaSeguroTrabajo, byte pagaAsignacionEstimulo, String contactoNombre, String contactoCorreo, String contactoTelefono) {
        this.localidades = localidades;
        this.empresaCuit = empresaCuit;
        this.empresaRazonSocial = empresaRazonSocial;
        this.pagaObraSocial = pagaObraSocial;
        this.pagaSeguroTrabajo = pagaSeguroTrabajo;
        this.pagaAsignacionEstimulo = pagaAsignacionEstimulo;
        this.contactoNombre = contactoNombre;
        this.contactoCorreo = contactoCorreo;
        this.contactoTelefono = contactoTelefono;
    }
    public Empresas(Localidades localidades, long empresaCuit, Date convenioFecha, Integer porcentajeGasto, String empresaRazonSocial, String empresaActividad, String empresaDireccion, String empresaCorreo, String empresaTelefono, String representanteNombre, Integer representanteDni, byte pagaObraSocial, byte pagaSeguroTrabajo, byte pagaAsignacionEstimulo, Date convenioFechaBaja, String motivoBaja, String password, byte[] archivoCm, String contactoNombre, String contactoCorreo, String contactoTelefono, Set ofertases, Set anexoses, Set estadocuentases, Set firmanteses, Set conveniosparticulareses) {
       this.localidades = localidades;
       this.empresaCuit = empresaCuit;
       this.convenioFecha = convenioFecha;
       this.porcentajeGasto = porcentajeGasto;
       this.empresaRazonSocial = empresaRazonSocial;
       this.empresaActividad = empresaActividad;
       this.empresaDireccion = empresaDireccion;
       this.empresaCorreo = empresaCorreo;
       this.empresaTelefono = empresaTelefono;
       this.representanteNombre = representanteNombre;
       this.representanteDni = representanteDni;
       this.pagaObraSocial = pagaObraSocial;
       this.pagaSeguroTrabajo = pagaSeguroTrabajo;
       this.pagaAsignacionEstimulo = pagaAsignacionEstimulo;
       this.convenioFechaBaja = convenioFechaBaja;
       this.motivoBaja = motivoBaja;
       this.password = password;
       this.archivoCm = archivoCm;
       this.contactoNombre = contactoNombre;
       this.contactoCorreo = contactoCorreo;
       this.contactoTelefono = contactoTelefono;
       this.ofertases = ofertases;
       this.anexoses = anexoses;
       this.estadocuentases = estadocuentases;
       this.firmanteses = firmanteses;
       this.conveniosparticulareses = conveniosparticulareses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Localidades getLocalidades() {
        return this.localidades;
    }
    
    public void setLocalidades(Localidades localidades) {
        this.localidades = localidades;
    }
    public long getEmpresaCuit() {
        return this.empresaCuit;
    }
    
    public void setEmpresaCuit(long empresaCuit) {
        this.empresaCuit = empresaCuit;
    }
    public Date getConvenioFecha() {
        return this.convenioFecha;
    }
    
    public void setConvenioFecha(Date convenioFecha) {
        this.convenioFecha = convenioFecha;
    }
    public Integer getPorcentajeGasto() {
        return this.porcentajeGasto;
    }
    
    public void setPorcentajeGasto(Integer porcentajeGasto) {
        this.porcentajeGasto = porcentajeGasto;
    }
    public String getEmpresaRazonSocial() {
        return this.empresaRazonSocial;
    }
    
    public void setEmpresaRazonSocial(String empresaRazonSocial) {
        this.empresaRazonSocial = empresaRazonSocial;
    }
    public String getEmpresaActividad() {
        return this.empresaActividad;
    }
    
    public void setEmpresaActividad(String empresaActividad) {
        this.empresaActividad = empresaActividad;
    }
    public String getEmpresaDireccion() {
        return this.empresaDireccion;
    }
    
    public void setEmpresaDireccion(String empresaDireccion) {
        this.empresaDireccion = empresaDireccion;
    }
    public String getEmpresaCorreo() {
        return this.empresaCorreo;
    }
    
    public void setEmpresaCorreo(String empresaCorreo) {
        this.empresaCorreo = empresaCorreo;
    }
    public String getEmpresaTelefono() {
        return this.empresaTelefono;
    }
    
    public void setEmpresaTelefono(String empresaTelefono) {
        this.empresaTelefono = empresaTelefono;
    }
    public String getRepresentanteNombre() {
        return this.representanteNombre;
    }
    
    public void setRepresentanteNombre(String representanteNombre) {
        this.representanteNombre = representanteNombre;
    }
    public Integer getRepresentanteDni() {
        return this.representanteDni;
    }
    
    public void setRepresentanteDni(Integer representanteDni) {
        this.representanteDni = representanteDni;
    }
    public byte getPagaObraSocial() {
        return this.pagaObraSocial;
    }
    
    public void setPagaObraSocial(byte pagaObraSocial) {
        this.pagaObraSocial = pagaObraSocial;
    }
    public byte getPagaSeguroTrabajo() {
        return this.pagaSeguroTrabajo;
    }
    
    public void setPagaSeguroTrabajo(byte pagaSeguroTrabajo) {
        this.pagaSeguroTrabajo = pagaSeguroTrabajo;
    }
    public byte getPagaAsignacionEstimulo() {
        return this.pagaAsignacionEstimulo;
    }
    
    public void setPagaAsignacionEstimulo(byte pagaAsignacionEstimulo) {
        this.pagaAsignacionEstimulo = pagaAsignacionEstimulo;
    }
    public Date getConvenioFechaBaja() {
        return this.convenioFechaBaja;
    }
    
    public void setConvenioFechaBaja(Date convenioFechaBaja) {
        this.convenioFechaBaja = convenioFechaBaja;
    }
    public String getMotivoBaja() {
        return this.motivoBaja;
    }
    
    public void setMotivoBaja(String motivoBaja) {
        this.motivoBaja = motivoBaja;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public byte[] getArchivoCm() {
        return this.archivoCm;
    }
    
    public void setArchivoCm(byte[] archivoCm) {
        this.archivoCm = archivoCm;
    }
    public String getContactoNombre() {
        return this.contactoNombre;
    }
    
    public void setContactoNombre(String contactoNombre) {
        this.contactoNombre = contactoNombre;
    }
    public String getContactoCorreo() {
        return this.contactoCorreo;
    }
    
    public void setContactoCorreo(String contactoCorreo) {
        this.contactoCorreo = contactoCorreo;
    }
    public String getContactoTelefono() {
        return this.contactoTelefono;
    }
    
    public void setContactoTelefono(String contactoTelefono) {
        this.contactoTelefono = contactoTelefono;
    }
    public Set getOfertases() {
        return this.ofertases;
    }
    
    public void setOfertases(Set ofertases) {
        this.ofertases = ofertases;
    }
    public Set getAnexoses() {
        return this.anexoses;
    }
    
    public void setAnexoses(Set anexoses) {
        this.anexoses = anexoses;
    }
    public Set getEstadocuentases() {
        return this.estadocuentases;
    }
    
    public void setEstadocuentases(Set estadocuentases) {
        this.estadocuentases = estadocuentases;
    }
    public Set getFirmanteses() {
        return this.firmanteses;
    }
    
    public void setFirmanteses(Set firmanteses) {
        this.firmanteses = firmanteses;
    }
    public Set getConveniosparticulareses() {
        return this.conveniosparticulareses;
    }
    
    public void setConveniosparticulareses(Set conveniosparticulareses) {
        this.conveniosparticulareses = conveniosparticulareses;
    }




}


