package utn.sau.hp.com.modelo;
// Generated 13/11/2014 15:37:16 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Estadocuentas generated by hbm2java
 */
public class Estadocuentas  implements java.io.Serializable {


     private Integer id;
     private Empresas empresas;
     private Date periodo;
     private Long nroMovimiento;
     private char tipoMovimiento;
     private long importe;
     private Date fecha;

    public Estadocuentas() {
    }

	
    public Estadocuentas(Empresas empresas, Date periodo, char tipoMovimiento, long importe, Date fecha) {
        this.empresas = empresas;
        this.periodo = periodo;
        this.tipoMovimiento = tipoMovimiento;
        this.importe = importe;
        this.fecha = fecha;
    }
    public Estadocuentas(Empresas empresas, Date periodo, Long nroMovimiento, char tipoMovimiento, long importe, Date fecha) {
       this.empresas = empresas;
       this.periodo = periodo;
       this.nroMovimiento = nroMovimiento;
       this.tipoMovimiento = tipoMovimiento;
       this.importe = importe;
       this.fecha = fecha;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public Date getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Date periodo) {
        this.periodo = periodo;
    }
    public Long getNroMovimiento() {
        return this.nroMovimiento;
    }
    
    public void setNroMovimiento(Long nroMovimiento) {
        this.nroMovimiento = nroMovimiento;
    }
    public char getTipoMovimiento() {
        return this.tipoMovimiento;
    }
    
    public void setTipoMovimiento(char tipoMovimiento) {
        this.tipoMovimiento = tipoMovimiento;
    }
    public long getImporte() {
        return this.importe;
    }
    
    public void setImporte(long importe) {
        this.importe = importe;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


