package utn.sau.hp.com.modelo;
// Generated 13/11/2014 15:37:16 by Hibernate Tools 3.6.0



/**
 * Localidades generated by hbm2java
 */
public class Localidades  implements java.io.Serializable {


     private int id;
     private int departamentoId;
     private String nombre;

    public Localidades() {
    }

    public Localidades(int id, int departamentoId, String nombre) {
       this.id = id;
       this.departamentoId = departamentoId;
       this.nombre = nombre;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getDepartamentoId() {
        return this.departamentoId;
    }
    
    public void setDepartamentoId(int departamentoId) {
        this.departamentoId = departamentoId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


