package utn.sau.hp.com.modelo;
// Generated 13/11/2014 15:37:16 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Materias generated by hbm2java
 */
public class Materias  implements java.io.Serializable {


     private Integer id;
     private int carreraId;
     private String materia;
     private Set requisitosmateriases = new HashSet(0);
     private Set alumnosmateriases = new HashSet(0);

    public Materias() {
    }

	
    public Materias(int carreraId, String materia) {
        this.carreraId = carreraId;
        this.materia = materia;
    }
    public Materias(int carreraId, String materia, Set requisitosmateriases, Set alumnosmateriases) {
       this.carreraId = carreraId;
       this.materia = materia;
       this.requisitosmateriases = requisitosmateriases;
       this.alumnosmateriases = alumnosmateriases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getCarreraId() {
        return this.carreraId;
    }
    
    public void setCarreraId(int carreraId) {
        this.carreraId = carreraId;
    }
    public String getMateria() {
        return this.materia;
    }
    
    public void setMateria(String materia) {
        this.materia = materia;
    }
    public Set getRequisitosmateriases() {
        return this.requisitosmateriases;
    }
    
    public void setRequisitosmateriases(Set requisitosmateriases) {
        this.requisitosmateriases = requisitosmateriases;
    }
    public Set getAlumnosmateriases() {
        return this.alumnosmateriases;
    }
    
    public void setAlumnosmateriases(Set alumnosmateriases) {
        this.alumnosmateriases = alumnosmateriases;
    }




}


