package utn.sau.hp.com.modelo;
// Generated 04/12/2014 23:31:51 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Materias generated by hbm2java
 */
public class Materias  implements java.io.Serializable {


     private Integer id;
     private Carreras carreras;
     private String materia;
     private Set alumnosmateriases = new HashSet(0);
     private Set requisitosmateriases = new HashSet(0);

    public Materias() {
    }

	
    public Materias(Carreras carreras, String materia) {
        this.carreras = carreras;
        this.materia = materia;
    }
    public Materias(Carreras carreras, String materia, Set alumnosmateriases, Set requisitosmateriases) {
       this.carreras = carreras;
       this.materia = materia;
       this.alumnosmateriases = alumnosmateriases;
       this.requisitosmateriases = requisitosmateriases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Carreras getCarreras() {
        return this.carreras;
    }
    
    public void setCarreras(Carreras carreras) {
        this.carreras = carreras;
    }
    public String getMateria() {
        return this.materia;
    }
    
    public void setMateria(String materia) {
        this.materia = materia;
    }
    public Set getAlumnosmateriases() {
        return this.alumnosmateriases;
    }
    
    public void setAlumnosmateriases(Set alumnosmateriases) {
        this.alumnosmateriases = alumnosmateriases;
    }
    public Set getRequisitosmateriases() {
        return this.requisitosmateriases;
    }
    
    public void setRequisitosmateriases(Set requisitosmateriases) {
        this.requisitosmateriases = requisitosmateriases;
    }




}


