package utn.sau.hp.com.modelo;
// Generated 13/11/2014 15:37:16 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ofertas generated by hbm2java
 */
public class Ofertas  implements java.io.Serializable {


     private Integer id;
     private Empresas empresas;
     private Date ofertaVigenciaDesde;
     private Date ofertaVigenciaHasta;
     private String ofertaDescripcion;
     private Set postulacioneses = new HashSet(0);
     private Set conveniosparticulareses = new HashSet(0);
     private Set ofertascarrerases = new HashSet(0);
     private Set requisitoscompetenciases = new HashSet(0);

    public Ofertas() {
    }

	
    public Ofertas(Empresas empresas, Date ofertaVigenciaDesde, Date ofertaVigenciaHasta, String ofertaDescripcion) {
        this.empresas = empresas;
        this.ofertaVigenciaDesde = ofertaVigenciaDesde;
        this.ofertaVigenciaHasta = ofertaVigenciaHasta;
        this.ofertaDescripcion = ofertaDescripcion;
    }
    public Ofertas(Empresas empresas, Date ofertaVigenciaDesde, Date ofertaVigenciaHasta, String ofertaDescripcion, Set postulacioneses, Set conveniosparticulareses, Set ofertascarrerases, Set requisitoscompetenciases) {
       this.empresas = empresas;
       this.ofertaVigenciaDesde = ofertaVigenciaDesde;
       this.ofertaVigenciaHasta = ofertaVigenciaHasta;
       this.ofertaDescripcion = ofertaDescripcion;
       this.postulacioneses = postulacioneses;
       this.conveniosparticulareses = conveniosparticulareses;
       this.ofertascarrerases = ofertascarrerases;
       this.requisitoscompetenciases = requisitoscompetenciases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public Date getOfertaVigenciaDesde() {
        return this.ofertaVigenciaDesde;
    }
    
    public void setOfertaVigenciaDesde(Date ofertaVigenciaDesde) {
        this.ofertaVigenciaDesde = ofertaVigenciaDesde;
    }
    public Date getOfertaVigenciaHasta() {
        return this.ofertaVigenciaHasta;
    }
    
    public void setOfertaVigenciaHasta(Date ofertaVigenciaHasta) {
        this.ofertaVigenciaHasta = ofertaVigenciaHasta;
    }
    public String getOfertaDescripcion() {
        return this.ofertaDescripcion;
    }
    
    public void setOfertaDescripcion(String ofertaDescripcion) {
        this.ofertaDescripcion = ofertaDescripcion;
    }
    public Set getPostulacioneses() {
        return this.postulacioneses;
    }
    
    public void setPostulacioneses(Set postulacioneses) {
        this.postulacioneses = postulacioneses;
    }
    public Set getConveniosparticulareses() {
        return this.conveniosparticulareses;
    }
    
    public void setConveniosparticulareses(Set conveniosparticulareses) {
        this.conveniosparticulareses = conveniosparticulareses;
    }
    public Set getOfertascarrerases() {
        return this.ofertascarrerases;
    }
    
    public void setOfertascarrerases(Set ofertascarrerases) {
        this.ofertascarrerases = ofertascarrerases;
    }
    public Set getRequisitoscompetenciases() {
        return this.requisitoscompetenciases;
    }
    
    public void setRequisitoscompetenciases(Set requisitoscompetenciases) {
        this.requisitoscompetenciases = requisitoscompetenciases;
    }




}


