package utn.sau.hp.com.modelo;
// Generated 13/11/2014 15:37:16 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * PagosOs generated by hbm2java
 */
public class PagosOs  implements java.io.Serializable {


     private Integer id;
     private Date fechapago;
     private long empresaCuit;
     private int nroLegajo;
     private int convenioParticularId;
     private Date periodo;

    public PagosOs() {
    }

	
    public PagosOs(long empresaCuit, int nroLegajo, int convenioParticularId, Date periodo) {
        this.empresaCuit = empresaCuit;
        this.nroLegajo = nroLegajo;
        this.convenioParticularId = convenioParticularId;
        this.periodo = periodo;
    }
    public PagosOs(Date fechapago, long empresaCuit, int nroLegajo, int convenioParticularId, Date periodo) {
       this.fechapago = fechapago;
       this.empresaCuit = empresaCuit;
       this.nroLegajo = nroLegajo;
       this.convenioParticularId = convenioParticularId;
       this.periodo = periodo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getFechapago() {
        return this.fechapago;
    }
    
    public void setFechapago(Date fechapago) {
        this.fechapago = fechapago;
    }
    public long getEmpresaCuit() {
        return this.empresaCuit;
    }
    
    public void setEmpresaCuit(long empresaCuit) {
        this.empresaCuit = empresaCuit;
    }
    public int getNroLegajo() {
        return this.nroLegajo;
    }
    
    public void setNroLegajo(int nroLegajo) {
        this.nroLegajo = nroLegajo;
    }
    public int getConvenioParticularId() {
        return this.convenioParticularId;
    }
    
    public void setConvenioParticularId(int convenioParticularId) {
        this.convenioParticularId = convenioParticularId;
    }
    public Date getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Date periodo) {
        this.periodo = periodo;
    }




}


