package utn.sau.hp.com.modelo;
// Generated 04/12/2014 23:31:51 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Postulaciones generated by hbm2java
 */
public class Postulaciones  implements java.io.Serializable {


     private Integer id;
     private Alumnos alumnos;
     private Ofertas ofertas;
     private Date fechaPostulacion;
     private Date fechaSeleccion;
     private byte cumpleRequisitosAcademicos;

    public Postulaciones() {
    }

    public Postulaciones(Alumnos alumnos, Ofertas ofertas, Date fechaPostulacion, Date fechaSeleccion, byte cumpleRequisitosAcademicos) {
       this.alumnos = alumnos;
       this.ofertas = ofertas;
       this.fechaPostulacion = fechaPostulacion;
       this.fechaSeleccion = fechaSeleccion;
       this.cumpleRequisitosAcademicos = cumpleRequisitosAcademicos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
    public Ofertas getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Ofertas ofertas) {
        this.ofertas = ofertas;
    }
    public Date getFechaPostulacion() {
        return this.fechaPostulacion;
    }
    
    public void setFechaPostulacion(Date fechaPostulacion) {
        this.fechaPostulacion = fechaPostulacion;
    }
    public Date getFechaSeleccion() {
        return this.fechaSeleccion;
    }
    
    public void setFechaSeleccion(Date fechaSeleccion) {
        this.fechaSeleccion = fechaSeleccion;
    }
    public byte getCumpleRequisitosAcademicos() {
        return this.cumpleRequisitosAcademicos;
    }
    
    public void setCumpleRequisitosAcademicos(byte cumpleRequisitosAcademicos) {
        this.cumpleRequisitosAcademicos = cumpleRequisitosAcademicos;
    }




}


