package utn.sau.hp.com.modelo;
// Generated 13/11/2014 15:37:16 by Hibernate Tools 3.6.0



/**
 * Provincias generated by hbm2java
 */
public class Provincias  implements java.io.Serializable {


     private int id;
     private String nombre;

    public Provincias() {
    }

    public Provincias(int id, String nombre) {
       this.id = id;
       this.nombre = nombre;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


