package utn.sau.hp.com.modelo;
// Generated 04/12/2014 23:31:51 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Provincias generated by hbm2java
 */
public class Provincias  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set departamentoses = new HashSet(0);

    public Provincias() {
    }

    public Provincias(String nombre, Set departamentoses) {
       this.nombre = nombre;
       this.departamentoses = departamentoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDepartamentoses() {
        return this.departamentoses;
    }
    
    public void setDepartamentoses(Set departamentoses) {
        this.departamentoses = departamentoses;
    }




}


