package utn.sau.hp.com.modelo;
// Generated 13/11/2014 15:37:16 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Reglamentaciones generated by hbm2java
 */
public class Reglamentaciones  implements java.io.Serializable {


     private Integer id;
     private String regDescripcion;
     private Date regFechaUltActualizacion;
     private byte[] regAdjunto;

    public Reglamentaciones() {
    }

    public Reglamentaciones(String regDescripcion, Date regFechaUltActualizacion, byte[] regAdjunto) {
       this.regDescripcion = regDescripcion;
       this.regFechaUltActualizacion = regFechaUltActualizacion;
       this.regAdjunto = regAdjunto;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRegDescripcion() {
        return this.regDescripcion;
    }
    
    public void setRegDescripcion(String regDescripcion) {
        this.regDescripcion = regDescripcion;
    }
    public Date getRegFechaUltActualizacion() {
        return this.regFechaUltActualizacion;
    }
    
    public void setRegFechaUltActualizacion(Date regFechaUltActualizacion) {
        this.regFechaUltActualizacion = regFechaUltActualizacion;
    }
    public byte[] getRegAdjunto() {
        return this.regAdjunto;
    }
    
    public void setRegAdjunto(byte[] regAdjunto) {
        this.regAdjunto = regAdjunto;
    }




}


