package utn.sau.hp.com.modelo;
// Generated 04/12/2014 23:31:51 by Hibernate Tools 3.6.0



/**
 * Requisitoscompetencias generated by hbm2java
 */
public class Requisitoscompetencias  implements java.io.Serializable {


     private Integer id;
     private Ofertas ofertas;
     private Competencias competencias;

    public Requisitoscompetencias() {
    }

    public Requisitoscompetencias(Ofertas ofertas, Competencias competencias) {
       this.ofertas = ofertas;
       this.competencias = competencias;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Ofertas getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Ofertas ofertas) {
        this.ofertas = ofertas;
    }
    public Competencias getCompetencias() {
        return this.competencias;
    }
    
    public void setCompetencias(Competencias competencias) {
        this.competencias = competencias;
    }




}


