package utn.sau.hp.com.modelo;
// Generated 04/12/2014 23:31:51 by Hibernate Tools 3.6.0



/**
 * Tareas generated by hbm2java
 */
public class Tareas  implements java.io.Serializable {


     private Integer id;
     private Conveniosparticulares conveniosparticulares;
     private Actividades actividades;
     private String tareaDescripcion;

    public Tareas() {
    }

    public Tareas(Conveniosparticulares conveniosparticulares, Actividades actividades, String tareaDescripcion) {
       this.conveniosparticulares = conveniosparticulares;
       this.actividades = actividades;
       this.tareaDescripcion = tareaDescripcion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Conveniosparticulares getConveniosparticulares() {
        return this.conveniosparticulares;
    }
    
    public void setConveniosparticulares(Conveniosparticulares conveniosparticulares) {
        this.conveniosparticulares = conveniosparticulares;
    }
    public Actividades getActividades() {
        return this.actividades;
    }
    
    public void setActividades(Actividades actividades) {
        this.actividades = actividades;
    }
    public String getTareaDescripcion() {
        return this.tareaDescripcion;
    }
    
    public void setTareaDescripcion(String tareaDescripcion) {
        this.tareaDescripcion = tareaDescripcion;
    }




}


