package utn.sau.hp.com.modelo;
// Generated 04/12/2014 23:31:51 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tutores generated by hbm2java
 */
public class Tutores  implements java.io.Serializable {


     private Integer id;
     private int dni;
     private String tutorEmail;
     private String tutorTelefono;
     private String tutorCargo;
     private String apellidoNombre;
     private long cuil;
     private Set conveniosparticulareses = new HashSet(0);
     private Set adendases = new HashSet(0);

    public Tutores() {
    }

	
    public Tutores(int dni, String apellidoNombre, long cuil) {
        this.dni = dni;
        this.apellidoNombre = apellidoNombre;
        this.cuil = cuil;
    }
    public Tutores(int dni, String tutorEmail, String tutorTelefono, String tutorCargo, String apellidoNombre, long cuil, Set conveniosparticulareses, Set adendases) {
       this.dni = dni;
       this.tutorEmail = tutorEmail;
       this.tutorTelefono = tutorTelefono;
       this.tutorCargo = tutorCargo;
       this.apellidoNombre = apellidoNombre;
       this.cuil = cuil;
       this.conveniosparticulareses = conveniosparticulareses;
       this.adendases = adendases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public String getTutorEmail() {
        return this.tutorEmail;
    }
    
    public void setTutorEmail(String tutorEmail) {
        this.tutorEmail = tutorEmail;
    }
    public String getTutorTelefono() {
        return this.tutorTelefono;
    }
    
    public void setTutorTelefono(String tutorTelefono) {
        this.tutorTelefono = tutorTelefono;
    }
    public String getTutorCargo() {
        return this.tutorCargo;
    }
    
    public void setTutorCargo(String tutorCargo) {
        this.tutorCargo = tutorCargo;
    }
    public String getApellidoNombre() {
        return this.apellidoNombre;
    }
    
    public void setApellidoNombre(String apellidoNombre) {
        this.apellidoNombre = apellidoNombre;
    }
    public long getCuil() {
        return this.cuil;
    }
    
    public void setCuil(long cuil) {
        this.cuil = cuil;
    }
    public Set getConveniosparticulareses() {
        return this.conveniosparticulareses;
    }
    
    public void setConveniosparticulareses(Set conveniosparticulareses) {
        this.conveniosparticulareses = conveniosparticulareses;
    }
    public Set getAdendases() {
        return this.adendases;
    }
    
    public void setAdendases(Set adendases) {
        this.adendases = adendases;
    }




}


