package utn.sau.hp.com.modelo;
// Generated 04/12/2014 23:31:51 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * UserDetails generated by hbm2java
 */
public class UserDetails  implements java.io.Serializable {


     private String id;
     private Users users;
     private float position;
     private String field;
     private String value;
     private String input;
     private String dataType;
     private String label;
     private Date created;
     private Date modified;

    public UserDetails() {
    }

	
    public UserDetails(String id, Users users, float position, String field, String input, String dataType, String label) {
        this.id = id;
        this.users = users;
        this.position = position;
        this.field = field;
        this.input = input;
        this.dataType = dataType;
        this.label = label;
    }
    public UserDetails(String id, Users users, float position, String field, String value, String input, String dataType, String label, Date created, Date modified) {
       this.id = id;
       this.users = users;
       this.position = position;
       this.field = field;
       this.value = value;
       this.input = input;
       this.dataType = dataType;
       this.label = label;
       this.created = created;
       this.modified = modified;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public float getPosition() {
        return this.position;
    }
    
    public void setPosition(float position) {
        this.position = position;
    }
    public String getField() {
        return this.field;
    }
    
    public void setField(String field) {
        this.field = field;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public String getInput() {
        return this.input;
    }
    
    public void setInput(String input) {
        this.input = input;
    }
    public String getDataType() {
        return this.dataType;
    }
    
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }




}


